# Generated by Django 5.1.1 on 2025-04-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_menuitem_client_delivery_menulist_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('ready', 'Ready for Pickup'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
